django/gnbproject/urls.py
# from django.contrib import admin
# from gnb import views
from baton.autodiscover import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
import notifications.urls
import gnb.views

urlpatterns = [
    path("", gnb.views.frontend_view, name="index"),
    path("gnb/dashboard/", gnb.views.my_dashboard_view, name="my_dashboard_view"),
    path(
        "gnb/accounts/<str:account_username>/", gnb.views.account_view, name="account_view"
    ),
    path("gnb/contact/", gnb.views.contact_view, name="contact_view"),
    path("gnb/expenses/", gnb.views.get_expenses_view, name="get_expenses_view"),
    path(
        "gnb/expenses/<int:expense_sheet_id>/",
        gnb.views.get_expense_sheet_view,
        name="get_expense_sheet_view",
    ),
    path(
        "gnb/transactions/<int:tx_id>/",
        gnb.views.get_transaction_view,
        name="get_transaction_view",
    ),
    path("gnb/send_new_comment/", gnb.views.send_new_comment, name="send_new_comment"),
    path("gnb/invoices/", gnb.views.get_invoices_view, name="get_invoices_view"),
    path(
        "gnb/invoices/<int:invoice_id>/",
        gnb.views.get_invoice_view,
        name="get_invoice_view",
    ),
    path(
        "gnb/invoices/<int:invoice_id>/edit/",
        gnb.views.get_invoice_view, {'edit': True},
        name="get_invoice_view_edit",
    ),
    path(
        "gnb/invoices/<int:invoice_id>/export/",
        gnb.views.download_invoice_facturae,
        name="download_invoice_facturae",
    ),
    path(
        "gnb/invoices/send_facturae_request/<int:invoice_id>/",
        gnb.views.send_facturae_request,
        name="send_facturae_request",
    ),
    path(
        "gnb/invoices/send_unpaid_notice/",
        gnb.views.send_invoice_unpaid_notice,
        name="send_invoice_unpaid_notice",
    ),
    path("gnb/reports/balance/", gnb.views.reports_balance_view, name="reports_balance_view"),
    path("gnb/report/users/", gnb.views.users_report_view, name="users_report_view"),
    path(
        "gnb/report/projects/",
        gnb.views.projects_report_view,
        name="projects_report_view",
    ),
    path("gnb/new_cashin/", gnb.views.new_cashin_view, name="new_cashin_view"),
    path("gnb/new_project/", gnb.views.new_project_view, name="new_project_view"),
    path(
        "gnb/projects/<str:project_code>/", gnb.views.project_view, name="project_view"
    ),
    path(
        "gnb/projects/<str:project_code>/new_invoice/",
        gnb.views.new_invoice_view,
        name="new_invoice_view",
    ),
    path(
        "gnb/projects/<str:project_code>/new_expense/",
        gnb.views.new_expense_view,
        name="new_expense_view",
    ),
    path("gnb/new_user/", gnb.views.new_user_view, name="new_user_view"),
    path(
        "gnb/payments/pending/",
        gnb.views.pending_payments,
        name="pending_payments_view",
    ),
    path(
        "gnb/payments/export/",
        gnb.views.export_payments,
        name="export_payments_view",
    ),
    path(
        "gnb/payments/mark_as_paid/",
        gnb.views.mark_as_paid_payments,
        name="mark_as_paid_payments_view",
    ),
    path(
        "gnb/payments/notify_about_tx_details/",
        gnb.views.notify_about_tx_details,
        name="notify_about_tx_details_view",
    ),

    path(
        "gnb/validate_iban/<str:iban_code>/",
        gnb.views.IBANValidatorView.as_view(),
        name="validate_iban",
    ),
    path("admin/", admin.site.urls),
    path("accounts/", include("django_registration.backends.one_step.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("baton/", include("baton.urls")),
    path("odoo/", include("odoo.urls")),
    path(
        "inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
    path("__debug__/", include("debug_toolbar.urls")),
]
# urlpatterns += static("api/media/", document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import os.path

    # settings.STATICFILES_DIRS += os.path.join(settings.BASE_DIR, "frontend","static"),
    # print('settings.STATICFILES_DIRS', settings.STATICFILES_DIRS)
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    FRONTEND_URL = "/static/"
    FRONTEND_ROOT_STATIC = os.path.join(settings.BASE_DIR, "gnb", "static")
    print("FRONTEND_ROOT_STATIC", FRONTEND_ROOT_STATIC)
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(FRONTEND_URL, document_root=FRONTEND_ROOT_STATIC)

django/odoo/urls.py
from django.urls import path
from . import views

app_name = "odoo"  # Opcional, pero útil para evitar conflictos de nombres

urlpatterns = [
    path("client_search/<str:client_info>/", views.client_search, name="client_search"),
    path("invoice/", views.InvoiceView.as_view(), name="invoice"),
    path(
        "invoice/edit_line/",
        views.edit_invoice_line,
        name="edit_invoice_line",
    ),
    path(
        "invoice/edit_client/",
        views.edit_invoice_contact,
        name="edit_invoice_contact",
    ),
    path(
        "invoice/validate/<int:invoice_id>/",
        views.validate_invoice,
        name="validate_invoice",
    ),
    path(
        "invoice/correct/<int:invoice_id>/",
        views.correct_invoice,
        name="correct_invoice",
    ),
    path(
        "invoice/duplicate/<int:invoice_id>/",
        views.duplicate_invoice,
        name="duplicate_invoice",
    ),
    path(
        "invoice/download/<int:invoice_id>/",
        views.download_invoice,
        name="download_invoice",
    ),
    path("expense/", views.ExpenseView.as_view(), name="expense"),
    path(
        "expense/validate/<int:expense_sheet_id>/",
        views.validate_expense_sheet,
        name="validate_expense",
    ),
    path("account_move/", views.BankAccountMoveView.as_view(), name="account_move"),
    path(
        "cash_account_move/",
        views.CashAccountMoveView.as_view(),
        name="cash_account_move",
    ),
    path(
        "delete_account_move/",
        views.delete_account_move,
        name="delete_account_move",
    ),
    path(
        "connection-status/",
        views.odoo_connection_status,
        name="odoo_connection_status",
    ),
]

django/templates/frontend/contact.html
{% extends "base.html" %}
{% block head %}
{% endblock %}
{% block title %}
<title>GNB Contacto</title>
{% endblock %}


{% block content %}

<div class="container mt-5">
  <h1>Formulario de Contacto</h1>
  <form id="form" method="post" action="/gnb/contact/">
    {% csrf_token %}
    <!-- Agregar campos del formulario aquí -->
    <div class="mb-3">
      <label for="mensaje" class="form-label">Mensaje:</label>
      <textarea class="form-control" id="contact_msg" name="contact_msg" rows="7"></textarea>
    </div>

    <hr class="my-4">
    <button class="w-100 btn btn-primary btn-lg" type="submit">Enviar</button>
  </form>
</div>


{% endblock %}

django/templates/frontend/get_expense.html
{% extends "base.html" %}
{% block head %}
<link rel="stylesheet" href="/static/css/print.css" />

<script>
  function get_taxid_name(id) {

    var taxIdNameMap = {
      42: 'IVA 4%', 43: 'IVA 10%',
      2: 'IVA 21%', 65: 'Exportación',
      47: 'Sin IVA 0%', 19: 'Servicio intracomunitario 0%',
      35: 'IVA Exento Repercutido No Sujeto'
    };

    // Return the name for the given ID
    return taxIdNameMap[id];
  }

  function printItem() {
    var content = document.getElementById("main_card").innerHTML;
    var originalBody = document.body.innerHTML;

    document.body.innerHTML = content;

    window.print();

    document.body.innerHTML = originalBody;
  }

</script>
{% endblock %}
{% block title %}
{% endblock %}

{% block content %}

<div class="container-fluid p-0">
  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb justify-content-end">
      {% if object.state == 'draft' %} 
        <li class="breadcrumb-item"><button class="btn btn-secondary btn-sm">Borrador</button></li>
      {% else %}
        <li class="breadcrumb-item"><button class="btn btn-outline-secondary btn-sm">Borrador</button></li>
        {% if object.state == 'approve' %} 
        <li class="breadcrumb-item"><button class="btn btn-secondary btn-sm">Esperando aprobación</button></li>
        {% elif object.state == 'done' %} 
        <li class="breadcrumb-item"><button class="btn btn-secondary btn-sm">Aprobada</button></li>
        {% elif object.state == 'cancel' %}
        <li class="breadcrumb-item"><button class="btn btn-secondary btn-sm">Rechazada</button></li>
        {% elif object.state == 'post' %}
        <li class="breadcrumb-item"><button class="btn btn-secondary btn-sm">A pagar</button></li>
        {% endif %}
      {% endif %}
    </ol>
  </nav>
</div>

<div class="card" id="main_card">
  <div class="card-body">
    <div class="container mb-5 mt-3">
      <div class="row d-flex align-items-baseline">
        <div class="col-sm-9">
            <h2>Hoja de Gasto nº {{object.name}}</h2>
            <h4 class="print-exclude">Creada por: {{object.employee_id.1}}</h4>
            <ul class="list-unstyled">
              <li class="text-muted">
                <i class="bi bi-calendar" style="color:#84B0CA ;"></i>
                <span class="fw-bold">Fecha: </span>{{object.accounting_date}}
              </li>
              {% if user.is_superuser %}
              <li class="text-muted"><i class="bi bi-box-arrow-up-right" style="color:#84B0CA ;"></i>
                 <a href="{{ODOO_DOMAIN}}/web?debug=1#id={{object.id}}&action=293&model=hr.expense.sheet&view_type=form" target="_blank">Enlace ODOO</a>
              </li>
              {% endif %}
            </ul>
        </div>
        <div class="no-print col-sm-3 float-end">
          <a class="btn btn-light text-capitalize border-0" data-mdb-ripple-color="dark"
            href="javascript:printItem();">
            <i class="bi bi-printer text-primary"></i> Imprimir</a>
            {% if user.is_superuser and object.state == 'approve' %}<a class="btn btn-light border-0" data-mdb-ripple-color="dark"
              href="{% url 'odoo:validate_expense' expense_sheet_id=object.id %}">
            <i class="bi bi-hand-thumbs-up-fill text-primary"></i> Aprobar y notificar</a>
            {% endif %}
        </div>
        <hr>
      </div>

      <div class="row my-2 mx-1 justify-content-center">
        <table class="table table-striped table-borderless">
          <thead style="background-color:#84B0CA ;" class="text-white">
            <tr>
              <th class="col">#</th>
              <th class="col">Descripción</th>
              <th class="col text-center">Cantidad</th>
              <th class="col text-center">Precio Unidad</th>
              <th class="col text-center">Impuestos</th>
              <th class="col text-center">Importe</th>
            </tr>
          </thead>
          <tbody>
            {% for move_line in move_lines %}
            <tr>
              <td class="fw-bold text-left">{{forloop.counter}}</td>
              <td>{{move_line.name}}</td>
              <td class="text-center">{{move_line.quantity}}</td>
              <td class="text-center">{{move_line.unit_amount}} €</td>
              <td class="text-center" id="taxNamesContainer-{{forloop.counter}}">
                {% for tax_id in move_line.tax_ids %}
                <script>
                  var taxName = get_taxid_name({{ tax_id }});
                  // Create a span element to hold the tax name
                  var spanElement = document.createElement('span');
                  spanElement.textContent = "(" + taxName + ")";
                  // Append the span to the container
                  document.getElementById('taxNamesContainer-{{forloop.parentloop.counter}}').appendChild(spanElement);

                </script>
                {% endfor %}
              </td>
              <td class="text-center">{{move_line.total_amount|floatformat:2}} €</td>
            </tr>
            {% endfor %}
          </tbody>

        </table>
      </div>
      <div class="row float-end text-end">
        <p>
          <span class="text-black me-3"> Total Impuestos</span>
          <span style="font-size: 22px;">{{object.taxed_amount|floatformat:2}} €</span>
        </p>

        <p class="text-black ">
          <span class="text-black me-3"> Importe total</span>
          <span style="font-size: 22px;">{{object.total_amount|floatformat:2}} €</span>

        </p>

      </div>
      
    </div>
  </div>
</div>
{% include "frontend/get_comments.html" %}
</div>


{% endblock %}

django/templates/frontend/get_invoices.html
{% extends "base.html" %}
{% block head %}
{% endblock %}
{% block title %}
<title>GNB Tus Facturas</title>
{% endblock %}

{% block content %}



<div class="py-5 text-center">
  <h2>Mis facturas</h2>
</div>


<table id="table" data-toggle="table" data-sort-name="total" data-sort-order="desc"
  class="table table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th data-field="fecha" data-sortable="true">Fecha</th>
      <th data-field="numero" data-sortable="true">Número</th>
      <th data-field="cliente" data-sortable="true">Cliente</th>
      <th data-field="total" data-sortable="true">Total(IVA incl.)</th>
      <th data-field="adeudado" data-sortable="true">Adeudado</th>
      <th data-field="estado" data-sortable="true">Estado</th>
    </tr>
  </thead>
  <tbody>
    {% for invoice in items%}
    <tr>
      <td>{{invoice.invoice_date}}</td>
      <td><a href="{% url 'get_invoice_view' invoice_id=invoice.id %}">
        {%if invoice.name == "/" %}{{CURRENT_YEAR}}/{{invoice.project_code}}/Pendiente
        {%else %}{{invoice.name}}{% endif %}</a></td>
      <td>{{invoice.partner_id.1}}</td>
      <td>{{invoice.amount_total_signed}}</td>
      <td>{{invoice.amount_residual_signed}}</td>
      <td>{%if invoice.state == 'posted' and invoice.invoice_payment_state == 'paid' %}Pagada
        {%elif invoice.state == 'posted' %} Aprobada
        {%elif invoice.state == 'draft' %} Borrador
        {%else %}{{invoice.state}}
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% block script %}

<script>
  // Add CSS classes to the rows based on the "Estado" column value

  document.addEventListener('DOMContentLoaded', function () {
    var tableRows = document.querySelectorAll('#table tbody tr');

    tableRows.forEach(function (row) {
      var deuda = row.querySelector('td:nth-child(5)').textContent.trim();
      var estado = row.querySelector('td:nth-child(6)').textContent.trim();
      var estadoCell = row.querySelector('td:nth-child(6)');
      var estado = estadoCell.textContent.trim();
      if (estado === 'posted') {
        row.classList.add('table-success');
      } else if (estado === 'cancel') {
        row.classList.add('table-danger');
      }
      if (estado === 'posted') {
        estadoCell.textContent = 'Enviada';
      }
      if (estado === 'cancel') {
        estadoCell.textContent = 'Cancelada';
      }
      if (deuda > 0) {
        row.classList.add('table-warning');
      }

      // Add more conditions for other states if needed
    });
  });
</script>


{% endblock %}

{% endblock %}

django/templates/frontend/get_transaction.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/print.css' %}" />
    
{% endblock %}
{% block title %}
{% endblock %}

{% block content %}

<div class="card mt-2" id="main_card">
  <div class="card-body">
    <div class="container mb-5 mt-3">
      <div class="row d-flex align-items-baseline">
        <div class="col-sm-7">
            <h2>Transacción nº {{transaction.name}} </h2>
            <ul class="list-unstyled">
              {% if user.is_superuser %}
              <li class="text-muted"><i class="bi bi-box-arrow-up-right" style="color:#84B0CA ;"></i>
                  <a href="{{ODOO_DOMAIN}}/web?debug=1#id={{transaction.id}}&action=216&model=account.move&view_type=form" target="_blank">Enlace ODOO</a>
              </li>
              {% endif %}
            </ul>
        </div>
        <div class="no-print col-sm-5 float-end">
          {% if transaction.state == 'posted' %}
          <a class="btn btn-light text-capitalize border-0 mb-2 w-100" data-mdb-ripple-color="dark"  href="javascript:printInvoice();">
          <i class="bi bi-printer text-primary"></i> Imprimir</a>
            {% if transaction.payment_scope == "external"%}
            <a class="btn btn-light border-0 mb-2 w-100" data-mdb-ripple-color="dark"  href="javascript:printReceipt();">
            <i class="bi bi-printer text-primary"></i> Imprimir justificante de pago</a>
            {% endif %}
          {% endif %}
        </div>
        <hr>
      </div>

      <div class="row my-2 justify-content-center">

        <table class="table table-striped table-bordered table-hover text-center">
          <tbody>
            <tr>
              <td class="fw-bold">Fecha</td>
              <td>{{transaction.date}}</td>
            </tr>
            <tr>
              <td class="fw-bold">Origen</td>
              <td>{{transaction.sender}}</td>
            </tr>
            <tr>
              <td class="fw-bold">Destino</td>
              <td>{{transaction.receiver}}</td>
            </tr>
            <tr>
              <td class="fw-bold">Total</td>
              <td>
                <span class="transaction-amount {% if transaction.state == 'cancel' %}strikethrough{% endif %} {% if not transaction.positive %}negative-amount{% endif %}">
                  {{transaction.amount_total}} €
                </span>
              </td>
            </tr>
            <tr>
              <td class="fw-bold">Referencia</td>
              <td>{{transaction.ref}}</td>
            </tr>
            <tr>
              <td class="fw-bold">Estado</td>
              <td>                
                {% if transaction.state == 'posted' %}
                Realizada
                {% elif transaction.state == 'cancel' %}
                Cancelada
                {% else %}
                {{transaction.state}}
                {% endif %}
              </td>
            </tr>
          </tbody>
        </table>

        {% if transaction.payment_scope == "external"%}

        <table class="table table-striped table-bordered table-hover text-center">
          <tbody>
            <tr class="text-left">
                <td colspan="2" class="fw-bold">Transferencia externa</td>
            </tr>
            <tr>
              <td class="fw-bold">Beneficiario</td>
              <td>
                {{transaction.payment_beneficiary}}
              </td>
            </tr>
            <tr>
              <td class="fw-bold">IBAN</td>
              <td>
                {{transaction.payment_iban}}
              </td>
            </tr>
          <tbody>
        </table>

        <!-- Table for print payment receipt -->
        <table class="table table-striped table-bordered table-hover text-center d-none" id="payment_receipt">
            <tbody>
              <tr class="text-left">
                  <td colspan="2" class="fw-bold">Justificante de transferencia de {{bank_name}}</td>
              </tr>
              <tr>
                <td class="fw-bold">Origen</td>
                <td>
                  {{organization_name}}
                </td>
              </tr>
              <tr>
                  <td class="fw-bold">Destino</td>
                  <td>
                    {{transaction.payment_iban}}
                  </td>
              </tr>
              <tr>
                <td class="fw-bold">Beneficiario</td>
                <td>
                  {{transaction.payment_beneficiary}}
                </td>
              </tr>
              <tr>
                <td class="fw-bold">Fecha</td>
                <td>
                  {{transaction.date}}
                </td>
              </tr>
              <tr>
                <td class="fw-bold">Concepto</td>
                <td>{{transaction.ref}}</td>
              </tr>
              <tr>
                <td class="fw-bold">Importe</td>
                <td>
                  {{transaction.amount_total}} €
                </td>
              </tr>
              <tr>
                <td class="fw-bold">Estado</td>
                <td>                
                  {% if transaction.state == 'posted' %}
                  Realizada
                  {% elif transaction.state == 'cancel' %}
                  Cancelada
                  {% else %}
                  {{transaction.state}}
                  {% endif %}
                </td>
              </tr>
            </tbody>
        </table>
        {% endif %}

      </div>

      <hr>
    </div>
  </div>
</div>
{% include "frontend/get_comments.html" %}
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/get-invoice-view.js' %}" type="text/javascript"></script>
{% endblock %}

django/templates/frontend/my_dashboard.html
{% extends "base.html" %}
{% load custom_filters %}
{% block head %}

{% endblock %}
{% block title %}
<title>GNB Mi Panel</title>
{% endblock %}

{% block content %}

<div class="row">
  <div class="p-3 d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="mb-0 text-gray-800">Panel de {{ user.first_name }} {{ user.last_name }}</h1>
  </div>
  
</div>
<hr />
<div class="row">

  <!-- Proyectos -->
  <div class="py-5 text-center">
    <h2>Mis Proyectos</h2>
    <hr>
  </div>
  <ul class="list-group project-list">
    <li class="list-group-item "  >
      <a class="big text-primary" href="{% url 'account_view' account_username=user_email %}{%if user_id %}?user={{user_id}}{%endif%}">CUENTA PERSONAL:  {{ user_email }}</a>
    </li>
    {% for project_code, project in user_projects.items %}
    <li class="list-group-item" >
      <a class="big" href="{% url 'project_view' project_code=project_code %}{%if user_id %}?user={{user_id}}{%endif%}">[{{ project_code }}] {{ project.name }}</a>
          {% if project.archived %}
            <span class="badge bg-secondary badge-sm"><i class="bi bi-database-fill-lock"></i> Archivado</span>
          {% endif %}
          {% if project.role == 'admin' %}
            <!-- <span class="badge bg-primary badge-sm">Admin</span> -->
            {% if not project.archived and project.can_invoice %}
              <a href="{% url 'new_invoice_view' project_code=project_code %}{%if user_id %}?user={{user_id}}{%endif%}">
                <span class="badge bg-danger badge-sm">+ Nueva Factura</span></a>
              <a href="{% url 'new_expense_view' project_code=project_code %}{%if user_id %}?user={{user_id}}{%endif%}">
                <span class="badge bg-warning badge-sm">+ Nuevo Gasto</span></a>
            {% endif %}
          {% endif %}
      </li>
    {% endfor %}
  </ul>
  <hr>


{% endblock %}

django/templates/frontend/portal_logged_in.html
{% extends "base.html" %}
<!DOCTYPE html>
<html>


<div class="container">
  <!-- Aquí puedes agregar el contenido de tu página -->
  <h1>Bienvenid@ a GNB</h1>
</div>
</body>

</html>

django/templates/frontend/portal_logged_out.html
{% extends "django_registration/registration_base.html" %}
{% load i18n static %}
{% block title %}{% trans "Bienvenid@ a GNB" %}{% endblock %}
 
    {% block content %}
        <h3>Bienvenid@ a <strong>GNB</strong></h3>
        <a href="/accounts/login/" class="btn btn-login btn-primary w-100 py-2">
            {% trans "Inicia sesión" %}
        </a>
        <p class="footer">
            GNB está desarrollado por <a href="https://komun.org/" target="_blank">Komun.org</a> y es 100% <a href="https://framagit.org/komun/gnb" target="_blank">software libre</a>.
        </p>
    {% endblock %}

django/templates/frontend/report_balance.html
{% extends "base.html" %}
{% load custom_filters %}
{% block head %}

{% endblock %}
{% block title %}
<title>GNB Mi Panel</title>
{% endblock %}

{% block content %}

<div class="py-5 text-center">
  <h1>Informe Balance: {{ project.name }} ({{project.code}})</h1>
</div>

<h4 class="text-center text-dark"><i class="text-dark bi bi-piggy-bank-fill"></i>Disponible: {{project_total.available_balance|floatformat:2}} €</h4>

  {%for account_code, account in cash_accounts.items %}
  <p class="text-center h6 mb-0">{{account.name}}: {{account.balance|floatformat:2}} €</p>
  {% endfor %}

  
{% endblock %}

django/templates/frontend/transaction_form.html
{% load static %}
<form method="post" id="new_account_move">
    <input type="hidden" id="user_id" name="user_id" value="{{user_id}}">
    <div class="row">
      <div class="col-sm">
        <input type="hidden" id="from_account" name="from_account" value="{{from_account}}" >
        <input type="hidden" id="available_balance" value="{{available_balance}}" >
        <h4 class="text-xs font-weight-bold text-dark mb-1 mt-3">
          Cuenta de destino
        </h4>
        <div>
          <input type="radio" id="internal_account" name="destination_type" value="internal_account" checked>
          <label for="internal_account">Cuenta Interna</label>
        </div>
        <select class="selectpicker mt-2" id="to_account_internal" name="to_account_internal"
          data-live-search="true" data-mdb-selected="['personal_account']" required>
          {%if from_account != user_email %}
            <option value="personal_account">Mi Cuenta Personal [{{user_email}}]</option>
          {% endif %}
          {% for k, v in all_accounts.items %}
            {%if k != from_account %}
              <option value="{{ k }}">[{{ k }}] {{v}}</option>
            {% endif %}
          {% endfor %}

        </select>
        <div>
          <input type="radio" id="external_account" name="destination_type" value="external_account">
          <label for="external_account">Cuenta Externa</label>
        </div>
        <input type="text" id="iban_account" name="iban_account" placeholder="Número de cuenta IBAN"
          class="form-control mt-2"><span id="iban-validation-result"></span>
          <input type="text" id="to_account_beneficiary" name="to_account_beneficiary" placeholder="Beneficiario/a"
          class="form-control mt-2">

        <div>
          <input type="radio" id="contributions" name="destination_type" value="contributions">
          <label for="contributions">Aportación al colectivo</label>
          <label class="red small hidden" id="contributions_label">Si puedes permitirlo, recuerda donar conscientemente al común de la cooperativa para hacerla sostenible. <a target="_blank" href="{{ project_total.why_contributions_url}}">Más información aquí.</a></label>
        </div>
        <div>
          <input type="radio" id="atm_withdrawal" name="destination_type" value="atm_withdrawal">
          <label for="external_account">Retirada en cajero</label> <small><a href="javascript:info_dimo()">¿Cómo funciona?</a></small>
        </div>
      </div>

      
      <div class="col-sm">
        <div class="row align-items-center">
          <!-- Columna para el label "Cantidad:" -->
          <div class="col-3">
            <h4 class="text-xs font-weight-bold text-dark mb-1">
              Cantidad:
            </h4>
          </div>
          <!-- Columna para el input y el símbolo € -->
          <div class="col-6">
            <div class="input-group cantidad-group">
              <input class="cantidad-input form-control" 
                     id="transfer_amount" name="transfer_amount" 
                     type="number" value=""
                     min="0" step="0.01" pattern="\d+(\.\d{1,2})?" 
                     placeholder="0" required />
              <span class="input-group-text cantidad-symbol">€</span>
            </div>
          </div>
        </div>
        <h4 class="text-xs font-weight-bold text-dark mb-1">
          Concepto:
        </h4>
        <textarea id="transfer_ref" name="transfer_ref" class="mt-3 form-control" rows="4"
                  aria-label="With textarea" placeholder="Escribe aquí el concepto o la referencia de la transacción." required></textarea>
        {% if user.is_superuser %}
          <div class="form-check">
            <input class="form-check-input" type="checkbox" name="avoid_notify" id="avoid_notify">
            <label class="form-check-label" for="avoid_notify">Evitar notificar a la cuenta receptora (Sólo admins)</label>
          </div>
        {% endif %}
      </div>
      
      
      <button type="button" class="w-90 btn btn-primary btn-lg mt-3" onclick="openConfirmPaymentModal()">
        <i class="bi bi-send"></i> Enviar transacción</button>
    </div>

  </form>
  <script src="{% static 'js/iban.js' %}?v={{APP_VERSION}}"></script>