django/gnbproject/urls.py
# from django.contrib import admin
# from gnb import views
from baton.autodiscover import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
import notifications.urls
import gnb.views

urlpatterns = [
    path("", gnb.views.frontend_view, name="index"),
    path("gnb/dashboard/", gnb.views.my_dashboard_view, name="my_dashboard_view"),
    path(
        "gnb/accounts/<str:account_username>/", gnb.views.account_view, name="account_view"
    ),
    path("gnb/contact/", gnb.views.contact_view, name="contact_view"),
    path("gnb/expenses/", gnb.views.get_expenses_view, name="get_expenses_view"),
    path(
        "gnb/expenses/<int:expense_sheet_id>/",
        gnb.views.get_expense_sheet_view,
        name="get_expense_sheet_view",
    ),
    path(
        "gnb/transactions/<int:tx_id>/",
        gnb.views.get_transaction_view,
        name="get_transaction_view",
    ),
    path("gnb/send_new_comment/", gnb.views.send_new_comment, name="send_new_comment"),
    path("gnb/invoices/", gnb.views.get_invoices_view, name="get_invoices_view"),
    path(
        "gnb/invoices/<int:invoice_id>/",
        gnb.views.get_invoice_view,
        name="get_invoice_view",
    ),
    path(
        "gnb/invoices/<int:invoice_id>/edit/",
        gnb.views.get_invoice_view, {'edit': True},
        name="get_invoice_view_edit",
    ),
    path(
        "gnb/invoices/<int:invoice_id>/export/",
        gnb.views.download_invoice_facturae,
        name="download_invoice_facturae",
    ),
    path(
        "gnb/invoices/send_facturae_request/<int:invoice_id>/",
        gnb.views.send_facturae_request,
        name="send_facturae_request",
    ),
    path(
        "gnb/invoices/send_unpaid_notice/",
        gnb.views.send_invoice_unpaid_notice,
        name="send_invoice_unpaid_notice",
    ),
    path("gnb/reports/balance/", gnb.views.reports_balance_view, name="reports_balance_view"),
    path("gnb/report/users/", gnb.views.users_report_view, name="users_report_view"),
    path(
        "gnb/report/projects/",
        gnb.views.projects_report_view,
        name="projects_report_view",
    ),
    path("gnb/new_cashin/", gnb.views.new_cashin_view, name="new_cashin_view"),
    path("gnb/new_project/", gnb.views.new_project_view, name="new_project_view"),
    path(
        "gnb/projects/<str:project_code>/", gnb.views.project_view, name="project_view"
    ),
    path(
        "gnb/projects/<str:project_code>/new_invoice/",
        gnb.views.new_invoice_view,
        name="new_invoice_view",
    ),
    path(
        "gnb/projects/<str:project_code>/new_expense/",
        gnb.views.new_expense_view,
        name="new_expense_view",
    ),
    path("gnb/new_user/", gnb.views.new_user_view, name="new_user_view"),
    path(
        "gnb/payments/pending/",
        gnb.views.pending_payments,
        name="pending_payments_view",
    ),
    path(
        "gnb/payments/export/",
        gnb.views.export_payments,
        name="export_payments_view",
    ),
    path(
        "gnb/payments/mark_as_paid/",
        gnb.views.mark_as_paid_payments,
        name="mark_as_paid_payments_view",
    ),
    path(
        "gnb/payments/notify_about_tx_details/",
        gnb.views.notify_about_tx_details,
        name="notify_about_tx_details_view",
    ),

    path(
        "gnb/validate_iban/<str:iban_code>/",
        gnb.views.IBANValidatorView.as_view(),
        name="validate_iban",
    ),
    path("admin/", admin.site.urls),
    path("accounts/", include("django_registration.backends.one_step.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("baton/", include("baton.urls")),
    path("odoo/", include("odoo.urls")),
    path(
        "inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
    path("__debug__/", include("debug_toolbar.urls")),
]
# urlpatterns += static("api/media/", document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import os.path

    # settings.STATICFILES_DIRS += os.path.join(settings.BASE_DIR, "frontend","static"),
    # print('settings.STATICFILES_DIRS', settings.STATICFILES_DIRS)
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    FRONTEND_URL = "/static/"
    FRONTEND_ROOT_STATIC = os.path.join(settings.BASE_DIR, "gnb", "static")
    print("FRONTEND_ROOT_STATIC", FRONTEND_ROOT_STATIC)
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(FRONTEND_URL, document_root=FRONTEND_ROOT_STATIC)

django/odoo/urls.py
from django.urls import path
from . import views

app_name = "odoo"  # Opcional, pero útil para evitar conflictos de nombres

urlpatterns = [
    path("client_search/<str:client_info>/", views.client_search, name="client_search"),
    path("invoice/", views.InvoiceView.as_view(), name="invoice"),
    path(
        "invoice/edit_line/",
        views.edit_invoice_line,
        name="edit_invoice_line",
    ),
    path(
        "invoice/edit_client/",
        views.edit_invoice_contact,
        name="edit_invoice_contact",
    ),
    path(
        "invoice/validate/<int:invoice_id>/",
        views.validate_invoice,
        name="validate_invoice",
    ),
    path(
        "invoice/correct/<int:invoice_id>/",
        views.correct_invoice,
        name="correct_invoice",
    ),
    path(
        "invoice/duplicate/<int:invoice_id>/",
        views.duplicate_invoice,
        name="duplicate_invoice",
    ),
    path(
        "invoice/download/<int:invoice_id>/",
        views.download_invoice,
        name="download_invoice",
    ),
    path("expense/", views.ExpenseView.as_view(), name="expense"),
    path(
        "expense/validate/<int:expense_sheet_id>/",
        views.validate_expense_sheet,
        name="validate_expense",
    ),
    path("account_move/", views.BankAccountMoveView.as_view(), name="account_move"),
    path(
        "cash_account_move/",
        views.CashAccountMoveView.as_view(),
        name="cash_account_move",
    ),
    path(
        "delete_account_move/",
        views.delete_account_move,
        name="delete_account_move",
    ),
    path(
        "connection-status/",
        views.odoo_connection_status,
        name="odoo_connection_status",
    ),
]

django/templates/base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="Aplicación Financiera descentralizada" />
    <meta name="author" content="Komun Team" />
    <script src="{% static 'js/jquery-3.5.1.min.js' %}" crossorigin="anonymous"></script>
    {% block title %} {% endblock %}
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/images/logo.png' %}" />
    <!-- Bootstrap CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.21.0/dist/bootstrap-table.min.css">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
    <link href="/static/css/bootstrap-select.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

    <!-- other head elements -->
    <script>
        function checkOdooConnection() {
            fetch('{% url "odoo:odoo_connection_status" %}')
                .then(response => response.json())
                .then(data => {
                    if (!data.is_connected) {
                        alert('Se perdió la conexión con el servidor de Odoo. El sistema se desactivará hasta que se restablezca la conexión. Contacta al círculo de administración.');
                        document.body.classList.add('screen-disabled');
                    } else {
                        document.body.classList.remove('screen-disabled');
                    }
                })
                .catch(error => {
                    console.error('Error checking Odoo connection:', error);
                    alert('Se perdió la conexión con el servidor de Odoo. El sistema se desactivará hasta que se restablezca la conexión. Contacta al círculo de administración.');
                });
        }

        //setInterval(checkOdooConnection, 60000*5); // Check every 5 min

        document.addEventListener('DOMContentLoaded', (event) => {
            checkOdooConnection(); // Initial check when the page loads
        });
    </script>

    {% block head %}{% endblock %}
</head>
<body>
    {% if DEV %}
    <div class="alert alert-warning" role="alert" >
        Versión Desarrollo de GNB <b>v{{APP_VERSION}}</b>. Base de datos: <b>{{CURRENT_DATABASE}}</b>
    </div>
    {% endif %}
    {% if messages %}
        {% for message in messages %}
        <div class="container-fluid p-0">
            <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
                <span aria-hidden="True">&times;</span>
                </button>
                {{ message|safe }}
            </div>
        </div>
        {% endfor %}
    {% endif %}
    {% include "frontend/menu.html" %}
    <div class="container" style="margin-bottom: 20px;">
    <main>
        {% block content %}{% endblock %}
    </main>
    </div>
    <div class="loader" id="loading-screen"></div>
    <div id="loading-overlay"></div>
    {% include "frontend/footer.html" %}

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-table@1.21.0/dist/bootstrap-table.min.js"></script>
    <script src="/static/js/bootstrap-select.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}?v={{APP_VERSION}}"></script>
    {% block script %}{% endblock %}

</body>
</html>